### ISSUE TITLE
Read light sensor value

### ISSUE THREAD

**Issue by waldo121** [ClubCedille/presence-detector#2]
Read light sensor value and turn on/off light accordingly.
When the room light is on the light must be on.
When the room light is off the light must be off.

**Comment by GRV96** [comment]
Issue fixed with commit _LED is on when light is detected._ in branch lightDetection.

**Comment by AXDOOMER** [comment]
Fix: https://github.com/ClubCedille/presence-detector/commit/5a68f8f7824a2c4f148f9dd36dbc49af39e0c0a4

**Comment by AXDOOMER** [comment]
Fixed in  https://github.com/ClubCedille/presence-detector/commit/5a68f8f7824a2c4f148f9dd36dbc49af39e0c0a4
